// モード名ラベル
export const MODE_LABELS: Record<string, { label: string; color: string; badge: string }> = {
  coach: { label: "戦略コーチ", color: "text-blue-400 bg-blue-900/30 border-blue-700", badge: "border-blue-600/60 text-blue-300 hover:bg-blue-900/30 hover:border-blue-500" },
  provocateur: { label: "悪魔の代弁者", color: "text-red-400 bg-red-900/30 border-red-700", badge: "border-red-600/60 text-red-300 hover:bg-red-900/30 hover:border-red-500" },
  analyst: { label: "冷徹アナリスト", color: "text-cyan-400 bg-cyan-900/30 border-cyan-700", badge: "border-cyan-600/60 text-cyan-300 hover:bg-cyan-900/30 hover:border-cyan-500" },
  philosopher: { label: "哲学者", color: "text-purple-400 bg-purple-900/30 border-purple-700", badge: "border-purple-600/60 text-purple-300 hover:bg-purple-900/30 hover:border-purple-500" },
  doctor: { label: "主治医", color: "text-green-400 bg-green-900/30 border-green-700", badge: "border-green-600/60 text-green-300 hover:bg-green-900/30 hover:border-green-500" },
  confidant: { label: "親友", color: "text-pink-400 bg-pink-900/30 border-pink-700", badge: "border-pink-600/60 text-pink-300 hover:bg-pink-900/30 hover:border-pink-500" },
  sensei: { label: "師匠", color: "text-amber-400 bg-amber-900/30 border-amber-700", badge: "border-amber-600/60 text-amber-300 hover:bg-amber-900/30 hover:border-amber-500" },
};

// 定型の問い（仕事＋人生）
// mode: coach=戦略コーチ, provocateur=悪魔の代弁者, analyst=冷徹アナリスト,
//       philosopher=哲学者, doctor=主治医, confidant=親友, sensei=師匠
export const presetQuestions = [
  // === 仕事：戦略・優先順位 === (coach)
  { id: "focus", label: "今、最も注力すべきは？", question: "今、俺が最も注力すべきことは何か？会社の優先課題と俺の強みを踏まえて教えてくれ。", mode: "coach" },
  { id: "blindspot", label: "盲点チェック", question: "今、俺が見落としている盲点は何か？会社の動きと俺の認識にズレはないか？", mode: "coach" },
  { id: "legacy-2030", label: "2030年までの戦略", question: "2030年までの仕事人生で、俺がやるべきことは何か？CDIOとして最大のレガシーを残すには？", mode: "coach" },
  { id: "legacy-2033", label: "2033年までの戦略", question: "2033年までを見据えて、俺がやるべきことは何か？CDIOとしてのキャリアの集大成をどう設計すべきか？", mode: "coach" },
  { id: "legacy-2035", label: "2035年までの戦略", question: "2035年までの長期ビジョンとして、俺はどんなレガシーを残すべきか？仕事人生の最終章をどう描くべきか？", mode: "coach" },
  { id: "weekly", label: "今週の振り返り", question: "今週、俺はLifeValue的に正しい選択ができていたか？来週の焦点は何にすべきか？", mode: "coach" },
  { id: "quarter", label: "今四半期の勝負どころ", question: "今四半期で俺が絶対に成し遂げるべき1〜3つのことは何か？", mode: "coach" },
  { id: "risk", label: "最大のリスクは？", question: "今、俺のキャリアや会社にとって最大のリスクは何か？どう備えるべきか？", mode: "coach" },
  { id: "decision-pending", label: "決断すべき案件", question: "今、俺が先送りにしている決断は何か？なぜ決められないのか？どう決めるべきか？", mode: "coach" },
  { id: "no-list", label: "やらないことリスト", question: "今の俺が「やらない」と決めるべきことは何か？断るべき依頼や手放すべき業務は？", mode: "coach" },
  { id: "win-quick", label: "クイックウィン", question: "今週中に達成できる、インパクトの大きい成果は何か？", mode: "coach" },
  { id: "cdio-value", label: "CDIO価値の最大化", question: "CDIOとしての俺の価値を最大化するために、今やるべきことは？", mode: "coach" },
  { id: "succession", label: "後継者育成", question: "俺の後継者として育てるべき人材は誰か？どう育成すべきか？", mode: "coach" },
  { id: "political", label: "社内政治の読み", question: "今、社内で起きている政治的な動きは何か？俺はどう立ち回るべきか？", mode: "coach" },
  // === 仕事：AI・テクノロジー === (analyst)
  { id: "ai-self", label: "AIで俺を強化", question: "AIを使って俺自身の生産性や意思決定力を上げるには？具体的なツールや使い方を教えてくれ。", mode: "analyst" },
  { id: "ai-team", label: "AIでチーム強化", question: "AIを活用してチームの生産性を上げるには？導入すべきツールや仕組みは？", mode: "analyst" },
  { id: "claude", label: "Claude活用法", question: "俺がClaudeをもっと有効活用するには？今見逃している使い方はあるか？", mode: "analyst" },
  { id: "tech-trend", label: "注目すべき技術", question: "今、俺が個人的にキャッチアップすべき技術トレンドは何か？", mode: "analyst" },
  { id: "ai-strategy", label: "AI戦略", question: "会社のAI戦略として、今最も重要な打ち手は何か？", mode: "analyst" },
  { id: "automation", label: "自動化すべき業務", question: "今、自動化すべき業務やプロセスは何か？優先順位は？", mode: "analyst" },
  { id: "tech-debt", label: "技術的負債", question: "今、対処すべき技術的負債は何か？いつ、どう返済すべきか？", mode: "analyst" },
  { id: "dx-progress", label: "DX進捗確認", question: "会社のDXは計画通り進んでいるか？遅れている部分とその原因は？", mode: "analyst" },
  // === 仕事：時間・集中 === (coach)
  { id: "time-waste", label: "時間の無駄撃ち", question: "俺が時間を無駄にしている習慣やタスクは何か？何をやめるべきか？", mode: "coach" },
  { id: "deep-work", label: "深い仕事の確保", question: "俺が深い集中時間を確保するにはどうすればいい？何を変えるべきか？", mode: "coach" },
  { id: "delegate", label: "委任すべき仕事", question: "俺がやっている仕事で、本来は委任すべきものは何か？", mode: "coach" },
  { id: "meeting-audit", label: "会議の見直し", question: "俺が出ている会議で、不要なものはどれか？減らすべき会議は？", mode: "coach" },
  { id: "interrupt", label: "割り込み対策", question: "俺の集中を妨げている割り込みは何か？どう防ぐべきか？", mode: "coach" },
  { id: "morning-routine", label: "朝の使い方", question: "朝の時間をもっと有効に使うには？今の使い方の問題点は？", mode: "coach" },
  // === 仕事：人間関係・影響力 === (coach)
  { id: "stakeholder", label: "ステークホルダー戦略", question: "今、俺が関係を強化すべき重要人物は誰か？どうアプローチすべきか？", mode: "coach" },
  { id: "influence", label: "影響力を高める", question: "俺の組織内での影響力を高めるには？何を変えるべきか？", mode: "coach" },
  { id: "mentor", label: "メンタリング", question: "俺が育成すべき人材は誰か？どう関わるべきか？", mode: "confidant" },
  { id: "conflict", label: "対立の解消", question: "今、俺が抱えている対立や摩擦は何か？どう解消すべきか？", mode: "confidant" },
  { id: "trust-build", label: "信頼構築", question: "俺への信頼を高めるために、今すべきことは何か？", mode: "coach" },
  { id: "communication", label: "伝え方の改善", question: "俺のコミュニケーションで改善すべき点は何か？誤解を生んでいないか？", mode: "coach" },
  // === 人生：全体設計 === (philosopher)
  { id: "life-design", label: "人生設計", question: "58歳の今、残りの人生をどう設計すべきか？仕事、家族、健康、趣味のバランスは？", mode: "philosopher" },
  { id: "life-priority", label: "人生の優先順位", question: "今の俺にとって、本当に大切なことは何か？何を優先し、何を手放すべきか？", mode: "philosopher" },
  { id: "regret-check", label: "後悔チェック", question: "このまま行くと、5年後に後悔しそうなことは何か？今から何を変えるべきか？", mode: "philosopher" },
  { id: "65-vision", label: "65歳の俺", question: "65歳になった時、どんな状態でいたいか？そのために今から何を準備すべきか？", mode: "philosopher" },
  { id: "70-vision", label: "70歳の俺", question: "70歳になった時、どんな生活を送っていたいか？仕事、趣味、社会との関わりは？", mode: "philosopher" },
  { id: "bucket-list", label: "死ぬまでにやりたいこと", question: "俺が死ぬまでにやりたいことは何か？今から始められることは？", mode: "philosopher" },
  { id: "life-theme", label: "人生のテーマ", question: "俺の人生のテーマは何か？何を追求し、何を残したいのか？", mode: "philosopher" },
  { id: "time-bucket", label: "タイムバケット", question: "今しかできないことは何か？5年後、10年後ではもう遅いことは？", mode: "philosopher" },
  // === 人生：家族・人間関係 === (confidant)
  { id: "family", label: "家族との関係", question: "家族との関係は良好か？もっと時間やエネルギーを割くべきか？", mode: "confidant" },
  { id: "important-people", label: "大切な人", question: "俺が大切にすべき人は誰か？その人たちとの関係を深めるには？", mode: "confidant" },
  { id: "isolation", label: "孤立防止", question: "俺は孤立していないか？仕事以外の人間関係は十分か？", mode: "confidant" },
  { id: "spouse", label: "配偶者との関係", question: "妻との関係は良好か？もっと時間を作るべきか？二人の時間の質は？", mode: "confidant" },
  { id: "friends", label: "友人関係", question: "俺には本当の友人がいるか？友人関係を深めるべきか？", mode: "confidant" },
  { id: "gratitude", label: "感謝を伝える", question: "俺が感謝を伝えるべき人は誰か？伝えていないことはないか？", mode: "confidant" },
  // === 人生：健康・フィジカル === (doctor)
  { id: "health", label: "健康状態", question: "俺の健康状態はどうか？身体が発しているサインを見逃していないか？", mode: "doctor" },
  { id: "running", label: "ランニング戦略", question: "ウルトラマラソンを続けるために、今の練習・休養・栄養は適切か？", mode: "doctor" },
  { id: "longevity", label: "長く動ける身体", question: "65歳以降も元気に動ける身体を作るために、今から何をすべきか？", mode: "doctor" },
  { id: "sleep", label: "睡眠の質", question: "俺の睡眠は十分か？睡眠の質を上げるために何をすべきか？", mode: "doctor" },
  { id: "recovery", label: "回復と休息", question: "俺は十分に回復できているか？休息の取り方は適切か？", mode: "doctor" },
  { id: "injury-prevention", label: "怪我予防", question: "怪我を予防するために、今やるべきことは何か？リスクの高い部位は？", mode: "doctor" },
  { id: "next-race", label: "次のレース戦略", question: "次のレースに向けて、どう準備すべきか？目標タイムと戦略は？", mode: "doctor" },
  { id: "nutrition", label: "栄養管理", question: "俺の食事・栄養は適切か？改善すべき点は？", mode: "doctor" },
  // === 人生：資産・経済 === (analyst)
  { id: "money", label: "資産設計", question: "65歳以降の経済的な準備は十分か？今から何をすべきか？", mode: "analyst" },
  { id: "freedom-money", label: "経済的自由", question: "働かなくても選択肢がある状態を作るには？今の資産形成は適切か？", mode: "analyst" },
  { id: "spending", label: "支出の見直し", question: "俺の支出で見直すべきものは何か？無駄遣いはないか？", mode: "analyst" },
  { id: "investment", label: "投資戦略", question: "今の投資戦略は適切か？リスク配分は？見直すべき点は？", mode: "analyst" },
  { id: "income-source", label: "収入源の多様化", question: "65歳以降の収入源をどう確保すべきか？今から準備できることは？", mode: "analyst" },
  { id: "insurance", label: "保険の見直し", question: "俺の保険は適切か？過不足はないか？見直すべき点は？", mode: "analyst" },
  // === 人生：学習・成長 === (sensei)
  { id: "curiosity", label: "好奇心の維持", question: "俺の好奇心は健在か？最近、心から面白いと思えたことは何か？", mode: "sensei" },
  { id: "new-challenge", label: "新しい挑戦", question: "俺が今から始めるべき新しい挑戦は何か？仕事以外で。", mode: "sensei" },
  { id: "skill-gap", label: "身につけるべきスキル", question: "俺が今から身につけるべきスキルは何か？仕事でも人生でも。", mode: "sensei" },
  { id: "reading", label: "読書計画", question: "俺が読むべき本は何か？今の読書習慣は十分か？", mode: "sensei" },
  { id: "learning-style", label: "学び方の最適化", question: "俺に合った学び方は何か？もっと効率的に学ぶには？", mode: "sensei" },
  { id: "mentor-find", label: "メンターを見つける", question: "俺が学ぶべき人は誰か？どうアプローチすべきか？", mode: "sensei" },
  // === 人生：意味・貢献 === (philosopher)
  { id: "meaning", label: "人生の意味", question: "俺の人生に意味を与えているものは何か？それは十分か？", mode: "philosopher" },
  { id: "contribution", label: "社会への貢献", question: "俺が次世代や社会に残せるものは何か？どう貢献すべきか？", mode: "philosopher" },
  { id: "knowledge-transfer", label: "知識の伝承", question: "俺の知識や経験を誰にどう伝えるべきか？残すべきものは？", mode: "sensei" },
  { id: "community", label: "コミュニティへの関与", question: "俺が関わるべきコミュニティは？どう貢献できるか？", mode: "sensei" },
  { id: "volunteer", label: "ボランティア活動", question: "俺ができるボランティアや社会貢献活動は何か？", mode: "philosopher" },
  { id: "writing", label: "書き残すべきこと", question: "俺が書き残すべきことは何か？本、ブログ、記録など。", mode: "sensei" },
  // === 共通：バランス・メンタル === (doctor/confidant)
  { id: "worklife", label: "仕事と生活", question: "俺の仕事と生活のバランスは適切か？家族との時間は十分か？", mode: "confidant" },
  { id: "burnout", label: "燃え尽き防止", question: "俺は燃え尽きに向かっていないか？ペースは持続可能か？", mode: "doctor" },
  { id: "energy", label: "エネルギー管理", question: "俺のエネルギーを最も消耗させているものは何か？どう対処すべきか？", mode: "doctor" },
  { id: "motivation", label: "モチベーション源", question: "今、俺のモチベーションを上げてくれるものは何か？下げているものは何か？", mode: "confidant" },
  { id: "stress-source", label: "ストレス源の特定", question: "今、俺のストレスの最大の原因は何か？どう対処すべきか？", mode: "doctor" },
  { id: "rumination", label: "反芻チェック", question: "俺は同じことを繰り返し考えていないか？頭から離れないことは何か？", mode: "doctor" },
  { id: "boundary", label: "境界線の確認", question: "俺の時間・尊厳・裁量を侵害しているものは何か？どう守るべきか？", mode: "confidant" },
  { id: "joy", label: "喜びの確認", question: "最近、俺が心から喜びを感じたことは何か？喜びが足りていないか？", mode: "confidant" },
  // === 追加：キャリア・転機 === (coach)
  { id: "career-pivot", label: "キャリア転換点", question: "今がキャリアの転換点だとしたら、どの方向に舵を切るべきか？", mode: "coach" },
  { id: "next-role", label: "次の役割", question: "CDIO後の俺の役割は何か？どんなポジションを目指すべきか？", mode: "coach" },
  { id: "exit-strategy", label: "出口戦略", question: "会社を去るとしたら、いつ、どのような形が理想か？", mode: "coach" },
  { id: "side-project", label: "副業・兼業", question: "今から始めるべき副業や兼業はあるか？どう準備すべきか？", mode: "coach" },
  { id: "board-position", label: "役員ポジション", question: "将来、社外取締役やアドバイザーとして活躍するには今何をすべきか？", mode: "coach" },
  { id: "consultant", label: "コンサル転身", question: "独立コンサルタントとしての可能性は？どの分野で勝負できるか？", mode: "coach" },
  { id: "startup", label: "起業の可能性", question: "俺が起業するとしたら、どの領域で何をすべきか？", mode: "coach" },
  { id: "acquisition", label: "買収・M&A視点", question: "俺の経験や人脈を活かして、どんなM&Aや事業買収に関われるか？", mode: "analyst" },
  // === 追加：ネットワーク・人脈 === (sensei)
  { id: "network-audit", label: "人脈の棚卸し", question: "俺の人脈で活用できていないものは？もっと深めるべき関係は？", mode: "sensei" },
  { id: "weak-ties", label: "弱い紐帯", question: "最近連絡を取っていない重要な人は誰か？再接続すべき人は？", mode: "sensei" },
  { id: "industry-network", label: "業界ネットワーク", question: "業界内での俺の存在感を高めるには？どのコミュニティに参加すべきか？", mode: "sensei" },
  { id: "cross-industry", label: "異業種交流", question: "異業種の人脈を広げるには？どの業界の人と繋がるべきか？", mode: "sensei" },
  { id: "alumni", label: "OB/OG活用", question: "俺の出身校や前職のネットワークをもっと活用できないか？", mode: "sensei" },
  { id: "linkedin", label: "LinkedIn戦略", question: "LinkedInなどのSNSをもっと活用するには？発信すべき内容は？", mode: "sensei" },
  { id: "introduce", label: "紹介すべき人", question: "俺の人脈の中で、お互いに紹介すべき人同士は誰か？", mode: "sensei" },
  { id: "event-attend", label: "参加すべきイベント", question: "今後参加すべきカンファレンスやイベントは何か？", mode: "sensei" },
  // === 追加：創造性・表現 === (sensei)
  { id: "creative-outlet", label: "創造的活動", question: "俺の創造性を発揮できる活動は何か？始めるべき趣味は？", mode: "sensei" },
  { id: "write-book", label: "本を書く", question: "俺が本を書くとしたら、どんなテーマで何を伝えるべきか？", mode: "sensei" },
  { id: "podcast", label: "ポッドキャスト", question: "俺がポッドキャストを始めるとしたら、どんな内容にすべきか？", mode: "sensei" },
  { id: "teaching", label: "教える活動", question: "大学や研修で教える機会を作るには？何を教えるべきか？", mode: "sensei" },
  { id: "art-culture", label: "芸術・文化", question: "俺が触れるべき芸術や文化は？感性を磨くには？", mode: "sensei" },
  { id: "music", label: "音楽との関わり", question: "音楽を通じて人生を豊かにするには？始めるべきことは？", mode: "sensei" },
  { id: "photography", label: "写真・映像", question: "写真や映像で何かを残すとしたら、何を撮るべきか？", mode: "sensei" },
  { id: "storytelling", label: "物語を伝える", question: "俺の人生の物語を誰かに伝えるとしたら、何を語るべきか？", mode: "sensei" },
  // === 追加：リーダーシップ・組織 === (coach)
  { id: "leadership-style", label: "リーダーシップスタイル", question: "俺のリーダーシップスタイルの強みと弱みは？変えるべき点は？", mode: "coach" },
  { id: "org-culture", label: "組織文化", question: "俺が組織文化に与えている影響は？もっと良くするには？", mode: "coach" },
  { id: "talent-attract", label: "人材獲得", question: "優秀な人材を惹きつけるために、俺ができることは何か？", mode: "coach" },
  { id: "diversity", label: "多様性推進", question: "組織の多様性を高めるために、俺がすべきことは？", mode: "coach" },
  { id: "remote-work", label: "リモートワーク", question: "リモートワーク時代に俺のリーダーシップはどう進化すべきか？", mode: "coach" },
  { id: "feedback", label: "フィードバック", question: "俺はチームに適切なフィードバックを与えているか？改善点は？", mode: "coach" },
  { id: "empowerment", label: "権限委譲", question: "俺はもっと権限を委譲すべきか？誰に何を任せるべきか？", mode: "coach" },
  { id: "vision-share", label: "ビジョン共有", question: "俺のビジョンはチームに伝わっているか？どう伝えるべきか？", mode: "coach" },
  // === 追加：交渉・説得 === (coach)
  { id: "negotiation", label: "交渉力", question: "俺の交渉力を高めるには？今抱えている交渉案件の戦略は？", mode: "coach" },
  { id: "persuasion", label: "説得術", question: "俺が説得すべき相手は誰か？どうアプローチすべきか？", mode: "coach" },
  { id: "presentation", label: "プレゼン力", question: "俺のプレゼンテーション能力を高めるには？", mode: "coach" },
  { id: "pitch", label: "ピッチ準備", question: "経営陣への次のピッチで、俺が伝えるべき核心は何か？", mode: "coach" },
  { id: "difficult-conv", label: "難しい会話", question: "俺が避けている難しい会話は何か？どう切り出すべきか？", mode: "coach" },
  { id: "say-no", label: "断る力", question: "俺が断るべきなのに断れていないことは何か？", mode: "coach" },
  { id: "ask-help", label: "助けを求める", question: "俺が助けを求めるべき相手は誰か？何を頼むべきか？", mode: "confidant" },
  { id: "conflict-resolve", label: "紛争解決", question: "組織内の対立を解決するために、俺がすべきことは？", mode: "coach" },
  // === 追加：危機管理・レジリエンス === (analyst)
  { id: "crisis-prep", label: "危機への備え", question: "今起こりうる最悪の事態は何か？どう備えるべきか？", mode: "analyst" },
  { id: "plan-b", label: "プランB", question: "今の計画が失敗した場合のプランBは？準備できているか？", mode: "analyst" },
  { id: "resilience", label: "回復力", question: "俺のレジリエンスを高めるには？困難から立ち直る力は十分か？", mode: "sensei" },
  { id: "failure-learn", label: "失敗からの学び", question: "最近の失敗から俺が学ぶべきことは何か？", mode: "sensei" },
  { id: "worst-case", label: "最悪シナリオ", question: "キャリアにおける最悪のシナリオは？それでも大丈夫か？", mode: "analyst" },
  { id: "insurance-life", label: "人生の保険", question: "俺の人生における保険は十分か？リスクヘッジできているか？", mode: "analyst" },
  { id: "reputation", label: "評判管理", question: "俺の評判を傷つけるリスクは何か？どう守るべきか？", mode: "analyst" },
  { id: "legal-risk", label: "法的リスク", question: "俺が気をつけるべき法的リスクは何か？", mode: "analyst" },
  // === 追加：業界・市場 === (analyst)
  { id: "industry-future", label: "業界の未来", question: "海運・海事業界の5年後はどうなっているか？どう備えるべきか？", mode: "analyst" },
  { id: "competition", label: "競合分析", question: "会社の最大の脅威となる競合は？俺は何をすべきか？", mode: "analyst" },
  { id: "market-shift", label: "市場の変化", question: "今起きている市場の変化で、俺が対応すべきものは？", mode: "analyst" },
  { id: "regulation", label: "規制動向", question: "今後の規制変更で注意すべきものは？どう準備するか？", mode: "analyst" },
  { id: "global-trend", label: "グローバルトレンド", question: "世界の潮流で、俺がキャッチアップすべきものは？", mode: "analyst" },
  { id: "china-factor", label: "中国ファクター", question: "中国の動向が俺の仕事に与える影響は？どう対応すべきか？", mode: "analyst" },
  { id: "sustainability-biz", label: "サステナビリティ事業", question: "サステナビリティをビジネス機会に変えるには？", mode: "analyst" },
  { id: "digital-disruption", label: "デジタル破壊", question: "業界のデジタルディスラプションにどう対応すべきか？", mode: "analyst" },
  // === 追加：自己理解・内省 === (philosopher)
  { id: "values-check", label: "価値観の確認", question: "俺の核となる価値観は何か？それに沿って生きているか？", mode: "philosopher" },
  { id: "strength-weakness", label: "強み弱み", question: "俺の真の強みと弱みは何か？客観的に見て。", mode: "philosopher" },
  { id: "blind-self", label: "自己の盲点", question: "俺が自分について知らないことは何か？他人から見た俺は？", mode: "philosopher" },
  { id: "fear", label: "恐れの正体", question: "俺が最も恐れていることは何か？その恐れは正当か？", mode: "philosopher" },
  { id: "ego-check", label: "エゴチェック", question: "俺のエゴが邪魔をしていることはないか？手放すべきものは？", mode: "philosopher" },
  { id: "authenticity", label: "本当の自分", question: "俺は本当の自分として生きているか？仮面を被っていないか？", mode: "philosopher" },
  { id: "life-review", label: "人生の振り返り", question: "58年の人生を振り返って、俺が学んだ最も重要なことは？", mode: "philosopher" },
  { id: "unfinished", label: "未完了のこと", question: "俺の人生で未完了のままになっていることは何か？完了させるべきか？", mode: "philosopher" },
  // === 追加：旅・体験 === (sensei)
  { id: "travel-next", label: "次の旅", question: "次に行くべき場所はどこか？なぜそこなのか？", mode: "sensei" },
  { id: "adventure", label: "冒険", question: "俺が挑戦すべき冒険的な体験は何か？", mode: "sensei" },
  { id: "experience-gift", label: "体験のギフト", question: "家族や大切な人と一緒にすべき体験は何か？", mode: "confidant" },
  { id: "solo-trip", label: "一人旅", question: "一人で行くべき場所や体験は？なぜ一人で行く必要があるか？", mode: "sensei" },
  { id: "nature", label: "自然との接点", question: "自然の中で過ごす時間は十分か？もっと増やすべきか？", mode: "sensei" },
  { id: "new-experience", label: "新しい体験", question: "今年中にすべき新しい体験は何か？", mode: "sensei" },
  { id: "cultural-immersion", label: "文化体験", question: "異文化に触れる機会は十分か？どこの文化を学ぶべきか？", mode: "sensei" },
  { id: "milestone-celebrate", label: "節目の祝い", question: "俺が祝うべき節目は何か？どう祝うべきか？", mode: "confidant" },
  // === 逆説・挑発：思考の枠を壊す === (provocateur)
  { id: "devil-advocate", label: "悪魔の代弁者", question: "俺が今「正しい」と信じていることの中で、実は間違っているものは何か？反論してくれ。", mode: "provocateur" },
  { id: "fire-yourself", label: "俺をクビにしろ", question: "もし俺が明日CDIOをクビになったら、後任は俺のやってきたことの何を真っ先に変えるか？", mode: "provocateur" },
  { id: "enemy-view", label: "敵の目で見ろ", question: "俺を潰したい競合やライバルがいるとしたら、俺の最大の弱点をどう突くか？", mode: "provocateur" },
  { id: "obituary", label: "俺の訃報記事", question: "明日死んだら、新聞の訃報に何と書かれるか？それは俺が望む内容か？足りないものは？", mode: "provocateur" },
  { id: "anti-pattern", label: "俺の悪癖パターン", question: "俺が繰り返し陥る失敗パターンは何か？同じ穴に落ち続けていないか？具体的に。", mode: "provocateur" },
  { id: "impostor", label: "インポスター告白", question: "俺が内心「バレたらまずい」と思っている能力の不足や虚勢は何か？正直に分析してくれ。", mode: "provocateur" },
  { id: "uncomfortable-truth", label: "不都合な真実", question: "俺について、周囲の人が思っているが面と向かって言えないことは何か？", mode: "provocateur" },
  { id: "sunk-cost", label: "サンクコスト監査", question: "俺が「ここまでやったから」という理由だけで続けているものは何か？今すぐ損切りすべきは？", mode: "provocateur" },
  // === 思考実験・フレームワーク === (provocateur)
  { id: "inversion", label: "逆転思考", question: "俺が最悪のCDIOになるには何をすればいい？その逆をやっているか？", mode: "provocateur" },
  { id: "10x-thinking", label: "10倍思考", question: "今の成果を10倍にするには？10%改善ではなく、根本的にやり方を変えるとしたら？", mode: "provocateur" },
  { id: "zero-base", label: "ゼロから再構築", question: "もし今日入社したばかりで、CDIOのポストに就いたとしたら、最初の90日で何をする？", mode: "provocateur" },
  { id: "time-travel", label: "10年前の俺へ", question: "10年前の自分に1つだけ忠告できるとしたら何と言う？そして10年後の俺は今の俺に何と言うか？", mode: "provocateur" },
  { id: "last-day", label: "最後の出社日", question: "今日が会社での最後の日だとしたら、俺は何を後悔し、何を誇りに思うか？", mode: "provocateur" },
  { id: "alien-perspective", label: "宇宙人の目", question: "地球に来た宇宙人が俺の日常を1週間観察したら、何を『非合理的だ』と指摘するか？", mode: "provocateur" },
  { id: "younger-self", label: "25歳の俺が見たら", question: "25歳の小山成生が今の俺を見たら、何に怒り、何に失望し、何に驚くか？", mode: "provocateur" },
  { id: "ceo-for-a-day", label: "社長を1日やるなら", question: "もし1日だけ社長の権限をもらえたら、会社に対して何をする？なぜそれを今提案していないのか？", mode: "provocateur" },
  // === 深層心理・本音 === (philosopher)
  { id: "midnight-thought", label: "深夜3時の不安", question: "深夜3時に目が覚めた時、俺の頭を支配する不安は何か？それは本当に対処不能なのか？", mode: "philosopher" },
  { id: "secret-desire", label: "言えない野望", question: "俺が人に言えない本当の野望は何か？なぜ言えないのか？実現可能か？", mode: "philosopher" },
  { id: "jealousy-signal", label: "嫉妬が教えること", question: "俺が最近、嫉妬を感じた相手は誰か？その嫉妬は俺の本当の欲求の何を教えてくれるか？", mode: "philosopher" },
  { id: "anger-decode", label: "怒りの翻訳", question: "最近、俺が強い怒りを感じた場面は？その怒りの裏にある本当の感情は何か？", mode: "philosopher" },
  { id: "permission-slip", label: "自分への許可証", question: "俺が自分に許可を出せていないことは何か？『これをやってもいい』と言ってやるべきことは？", mode: "philosopher" },
  { id: "guilty-pleasure", label: "後ろめたい喜び", question: "俺が密かに楽しんでいるが、恥ずかしくて人に言えないことは何か？それは本当に恥ずべきことか？", mode: "philosopher" },
  { id: "pretending", label: "演技をやめたら", question: "俺が仕事で演技している部分は何か？その仮面を外したら何が起きるか？", mode: "philosopher" },
  // === 関係性の深堀り === (confidant)
  { id: "toxic-relationship", label: "毒になる関係", question: "俺のエネルギーを奪っている人間関係は何か？距離を置くべき相手はいるか？", mode: "confidant" },
  { id: "unsaid-words", label: "言えなかった言葉", question: "俺が誰かに言うべきだったのに言えなかった言葉は何か？今からでも伝えるべきか？", mode: "confidant" },
  { id: "apology-owed", label: "借りている謝罪", question: "俺が誰かに謝るべきなのに、まだ謝っていないことは何か？", mode: "confidant" },
  { id: "who-needs-me", label: "俺を必要としてる人", question: "今、本当に俺を必要としている人は誰か？俺はその人に十分に応えているか？", mode: "confidant" },
  // === 逆張り戦略 === (provocateur)
  { id: "do-nothing", label: "何もしない選択", question: "もし俺が向こう3ヶ月、新しいことを一切始めず今あるものだけに集中したら何が起きるか？", mode: "provocateur" },
  { id: "embrace-chaos", label: "混乱を抱きしめろ", question: "俺が必死にコントロールしようとしているが、実は手放した方がうまくいくものは何か？", mode: "provocateur" },
  { id: "be-wrong", label: "間違える勇気", question: "俺が『間違えたくない』と思うあまり動けていないことは何か？間違えた場合の最悪の結果は？", mode: "provocateur" },
  { id: "slow-down", label: "遅くしてみろ", question: "俺がスピードを求めすぎて壊しているものは何か？あえてゆっくりやるべきことは？", mode: "provocateur" },
  { id: "quit-something", label: "辞める美学", question: "今、勇気を持って辞めるべきことは何か？続けることが美徳とは限らない。何を手放す？", mode: "provocateur" },
  { id: "boring-solution", label: "つまらない正解", question: "俺が派手な解決策ばかり追い求めて見逃している、地味だが確実な打ち手は何か？", mode: "provocateur" },
  // === 身体知・直感 === (doctor)
  { id: "gut-feeling", label: "直感は何と言ってる", question: "頭では正しいとわかっているが、腹の底で違和感を感じていることは何か？その直感を信じるべきか？", mode: "doctor" },
  { id: "body-signal", label: "身体が出すサイン", question: "最近、身体が出している警告サインは何か？肩の凝り、胃の重さ、不眠…それは何を意味するか？", mode: "doctor" },
  { id: "flow-state", label: "ゾーンに入る条件", question: "俺が最後にフロー状態を経験したのはいつか？その条件を意図的に再現するには？", mode: "doctor" },
  // === 死角を突く問い === (provocateur)
  { id: "what-if-ai-replaces", label: "AIに俺が要らない日", question: "5年後、AIがCDIOの仕事の80%をこなせるようになったら、俺の存在価値は何に変わるか？", mode: "provocateur" },
  { id: "company-without-me", label: "俺なしの会社", question: "俺が明日いなくなっても会社は回るか？回るなら俺の本当の価値はどこにある？回らないならそれは組織の欠陥では？", mode: "provocateur" },
  { id: "success-trap", label: "成功の罠", question: "過去の成功体験が、今の俺の足かせになっていることは何か？成功パターンへの執着が新しい可能性を殺していないか？", mode: "provocateur" },
  { id: "privilege-check", label: "特権の自覚", question: "俺が当たり前だと思っているが、実は恵まれた立場ゆえのものは何か？その自覚が足りないせいで見えないものは？", mode: "provocateur" },
  { id: "decay-check", label: "腐り始めの兆候", question: "俺の思考やスキルで、すでに陳腐化が始まっているものは何か？まだ気づいていない劣化は？", mode: "provocateur" },
  { id: "paradox", label: "矛盾を直視しろ", question: "俺が同時に信じている矛盾した信念は何か？その矛盾を解消する必要があるか、共存させるべきか？", mode: "provocateur" },
];
